{
 "title": "Ingate SIP stats - InfluxDB based",
 "description": "Stats panel for Ingate SBCs - for InfluxDB back-end",
 "tags": [
  "Ingate",
  "SBC"
 ],
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "devname",
    "label": "Device",
    "query": "show tag values with key=\"host\""
   },
   {
    "name": "cpu_value",
    "label": "CPU",
    "query": "show tag values from cpu_value with key=\"instance\" where \"host\" =~ /^$devname$/"
   },
   {
    "name": "interface",
    "label": "Interface",
    "query": "show tag values from interface_rx with key=\"instance\" where \"host\" =~ /^$devname$/"
   }
  ]
 },
 "panels": [
  {
   "title": "Host Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Memory Usage on $devname",
   "type": "timeseries",
   "description": "The autogen table contains either memory_value or memory table, depending on how your (telegraf) collectd receiver is configured. Displaying all of the queries is harmless.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "Used",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$devname$/" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "used" }
     ]
    },
    {
     "alias": "Slab Unrecl.",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$devname$/" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "slab_unrecl" }
     ]
    },
    {
     "alias": "Slab Recl.",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$devname$/" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "slab_recl" }
     ]
    },
    {
     "alias": "Buffered",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$devname$/" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "buffered" }
     ]
    },
    {
     "alias": "Cached",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$devname$/" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "cached" }
     ]
    },
    {
     "alias": "Free",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$devname$/" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "free" }
     ]
    },
    {
     "alias": "Used",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$devname$/" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "used" }
     ]
    },
    {
     "alias": "Slab Unrecl.",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$devname$/" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "slab_unrecl" }
     ]
    },
    {
     "alias": "Slab Recl.",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$devname$/" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "slab_recl" }
     ]
    },
    {
     "alias": "Buffered",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$devname$/" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "buffered" }
     ]
    },
    {
     "alias": "Cached",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$devname$/" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "cached" }
     ]
    },
    {
     "alias": "Free",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$devname$/" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "free" }
     ]
    }
   ]
  },
  {
   "title": "Host Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {}
   ]
  },
  {
   "title": "$interface octets/sec on $devname",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 10 },
   "repeat": "interface",
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "alias": "Receive",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "interface_rx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$devname$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "if_octets" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$interface$/" }
     ]
    },
    {
     "alias": "Transmit",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "interface_tx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$devname$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "if_octets" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$interface$/" }
     ]
    }
   ]
  },
  {
   "title": "$interface packets/sec on $devname",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
   "repeat": "interface",
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "alias": "Rx",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "interface_rx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$devname$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "if_packets" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$interface$/" }
     ]
    },
    {
     "alias": "Tx",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "interface_tx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$devname$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "if_packets" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$interface$/" }
     ]
    },
    {
     "alias": "Dropped (Rx)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "interface_rx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$devname$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "if_dropped" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$interface$/" }
     ]
    },
    {
     "alias": "Errors",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "interface_tx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$devname$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "if_errors" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$interface$/" }
     ]
    },
    {
     "alias": "MCast",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "interface_tx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$devname$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "if_mcast" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$interface$/" }
     ]
    }
   ]
  },
  {
   "title": "Host CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {}
   ]
  },
  {
   "title": "System Load on $devname",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 23, "x": 1, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "1 min",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "load_shortterm",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$devname$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "load" }
     ]
    },
    {
     "alias": "5 min",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "load_midterm",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$devname$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "load" }
     ]
    },
    {
     "alias": "15 min",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "load_longterm",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$devname$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "load" }
     ]
    }
   ]
  },
  {
   "title": "CPU ($cpu_value) usage on $devname",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 34 },
   "repeat": "cpu_value",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "Steal",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "type_instance" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cpu_value",
     "query": "SELECT non_negative_derivative(mean(\"value\"), 10s)  / 10 FROM \"autogen\".\"cpu_value\" WHERE (\"host\" =~ /^$devname$/ AND \"type_instance\" = 'steal') AND $timeFilter GROUP BY time($__interval), \"type_instance\" fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$devname$/" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "steal" }
     ]
    },
    {
     "alias": "SoftIRQ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "type_instance" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cpu_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$devname$/" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "softirq" }
     ]
    },
    {
     "alias": "System",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "type_instance" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cpu_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$devname$/" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "system" }
     ]
    },
    {
     "alias": "Wait-IO",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "type_instance" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cpu_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$devname$/" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "wait" }
     ]
    },
    {
     "alias": "User",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "type_instance" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cpu_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$devname$/" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "user" }
     ]
    },
    {
     "alias": "Nice",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "type_instance" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cpu_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$devname$/" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "nice" }
     ]
    },
    {
     "alias": "Idle",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "type_instance" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cpu_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$devname$/" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "idle" }
     ]
    }
   ]
  },
  {
   "title": "SIP Counters",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "targets": [
    {}
   ]
  },
  {
   "title": "24H Ingress Totals",
   "type": "timeseries",
   "description": "Shows cumulative totals for 24hour periods for each method type",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "pkts" } },
   "targets": [
    {
     "alias": "ACK",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ingate_value",
     "query": "SELECT count(\"value\") FROM \"autogen\".\"ingate_value\" WHERE (\"host\" =~ /^$devname$/ AND \"instance\" = 'sip-message' AND \"type\" = 'count' AND \"type_instance\" = 'INVITE-RX') AND $timeFilter GROUP BY time(24h) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "24h" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$devname$/" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "sip-message" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "count" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "ACK-RX" }
     ]
    },
    {
     "alias": "BYE",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ingate_value",
     "query": "SELECT count(\"value\") FROM \"autogen\".\"ingate_value\" WHERE (\"host\" =~ /^$devname$/ AND \"instance\" = 'sip-message' AND \"type\" = 'count' AND \"type_instance\" = 'INVITE-RX') AND $timeFilter GROUP BY time(24h) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "24h" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$devname$/" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "sip-message" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "count" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "BYE-RX" }
     ]
    },
    {
     "alias": "CAN",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ingate_value",
     "query": "SELECT count(\"value\") FROM \"autogen\".\"ingate_value\" WHERE (\"host\" =~ /^$devname$/ AND \"instance\" = 'sip-message' AND \"type\" = 'count' AND \"type_instance\" = 'INVITE-RX') AND $timeFilter GROUP BY time(24h) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "24h" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$devname$/" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "sip-message" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "count" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "CANCEL-RX" }
     ]
    },
    {
     "alias": "INF",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ingate_value",
     "query": "SELECT count(\"value\") FROM \"autogen\".\"ingate_value\" WHERE (\"host\" =~ /^$devname$/ AND \"instance\" = 'sip-message' AND \"type\" = 'count' AND \"type_instance\" = 'INVITE-RX') AND $timeFilter GROUP BY time(24h) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "24h" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$devname$/" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "sip-message" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "count" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "INFO-RX" }
     ]
    },
    {
     "alias": "INV",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ingate_value",
     "query": "SELECT count(\"value\") FROM \"autogen\".\"ingate_value\" WHERE (\"host\" =~ /^$devname$/ AND \"instance\" = 'sip-message' AND \"type\" = 'count' AND \"type_instance\" = 'INVITE-RX') AND $timeFilter GROUP BY time(24h) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "24h" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$devname$/" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "sip-message" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "count" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "INVITE-RX" }
     ]
    },
    {
     "alias": "MSG",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ingate_value",
     "query": "SELECT count(\"value\") FROM \"autogen\".\"ingate_value\" WHERE (\"host\" =~ /^$devname$/ AND \"instance\" = 'sip-message' AND \"type\" = 'count' AND \"type_instance\" = 'INVITE-RX') AND $timeFilter GROUP BY time(24h) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "24h" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$devname$/" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "sip-message" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "count" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "MESSAGE-RX" }
     ]
    },
    {
     "alias": "MSG",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ingate_value",
     "query": "SELECT count(\"value\") FROM \"autogen\".\"ingate_value\" WHERE (\"host\" =~ /^$devname$/ AND \"instance\" = 'sip-message' AND \"type\" = 'count' AND \"type_instance\" = 'INVITE-RX') AND $timeFilter GROUP BY time(24h) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "24h" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$devname$/" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "sip-message" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "count" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "NOTIFY-RX" }
     ]
    },
    {
     "alias": "OPT",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ingate_value",
     "query": "SELECT count(\"value\") FROM \"autogen\".\"ingate_value\" WHERE (\"host\" =~ /^$devname$/ AND \"instance\" = 'sip-message' AND \"type\" = 'count' AND \"type_instance\" = 'INVITE-RX') AND $timeFilter GROUP BY time(24h) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "24h" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$devname$/" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "sip-message" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "count" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "OPTIONS-RX" }
     ]
    },
    {
     "alias": "PRK",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ingate_value",
     "query": "SELECT count(\"value\") FROM \"autogen\".\"ingate_value\" WHERE (\"host\" =~ /^$devname$/ AND \"instance\" = 'sip-message' AND \"type\" = 'count' AND \"type_instance\" = 'INVITE-RX') AND $timeFilter GROUP BY time(24h) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "24h" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$devname$/" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "sip-message" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "count" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "PRACK-RX" }
     ]
    },
    {
     "alias": "PUB",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ingate_value",
     "query": "SELECT count(\"value\") FROM \"autogen\".\"ingate_value\" WHERE (\"host\" =~ /^$devname$/ AND \"instance\" = 'sip-message' AND \"type\" = 'count' AND \"type_instance\" = 'INVITE-RX') AND $timeFilter GROUP BY time(24h) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "24h" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$devname$/" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "sip-message" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "count" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "PUBLISH-RX" }
     ]
    },
    {
     "alias": "REF",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ingate_value",
     "query": "SELECT count(\"value\") FROM \"autogen\".\"ingate_value\" WHERE (\"host\" =~ /^$devname$/ AND \"instance\" = 'sip-message' AND \"type\" = 'count' AND \"type_instance\" = 'INVITE-RX') AND $timeFilter GROUP BY time(24h) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "24h" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$devname$/" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "sip-message" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "count" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "REFER-RX" }
     ]
    },
    {
     "alias": "REG",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ingate_value",
     "query": "SELECT count(\"value\") FROM \"autogen\".\"ingate_value\" WHERE (\"host\" =~ /^$devname$/ AND \"instance\" = 'sip-message' AND \"type\" = 'count' AND \"type_instance\" = 'INVITE-RX') AND $timeFilter GROUP BY time(24h) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "24h" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$devname$/" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "sip-message" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "count" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "REGISTER-RX" }
     ]
    },
    {
     "alias": "SUB",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ingate_value",
     "query": "SELECT count(\"value\") FROM \"autogen\".\"ingate_value\" WHERE (\"host\" =~ /^$devname$/ AND \"instance\" = 'sip-message' AND \"type\" = 'count' AND \"type_instance\" = 'INVITE-RX') AND $timeFilter GROUP BY time(24h) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "24h" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$devname$/" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "sip-message" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "count" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "SUBSCRIBE-RX" }
     ]
    },
    {
     "alias": "UNK",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ingate_value",
     "query": "SELECT count(\"value\") FROM \"autogen\".\"ingate_value\" WHERE (\"host\" =~ /^$devname$/ AND \"instance\" = 'sip-message' AND \"type\" = 'count' AND \"type_instance\" = 'INVITE-RX') AND $timeFilter GROUP BY time(24h) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "24h" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$devname$/" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "sip-message" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "count" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "UNKNOWN-RX" }
     ]
    }
   ]
  },
  {
   "title": "24H Egress Totals",
   "type": "timeseries",
   "description": "Shows cumulative totals for 24hour periods for each method type",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "pkts" } },
   "targets": [
    {
     "alias": "ACK",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ingate_value",
     "query": "SELECT count(\"value\") FROM \"autogen\".\"ingate_value\" WHERE (\"host\" =~ /^$devname$/ AND \"instance\" = 'sip-message' AND \"type\" = 'count' AND \"type_instance\" = 'INVITE-RX') AND $timeFilter GROUP BY time(24h) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "24h" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$devname$/" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "sip-message" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "count" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "ACK-TX" }
     ]
    },
    {
     "alias": "BYE",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ingate_value",
     "query": "SELECT count(\"value\") FROM \"autogen\".\"ingate_value\" WHERE (\"host\" =~ /^$devname$/ AND \"instance\" = 'sip-message' AND \"type\" = 'count' AND \"type_instance\" = 'INVITE-RX') AND $timeFilter GROUP BY time(24h) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "24h" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$devname$/" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "sip-message" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "count" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "BYE-TX" }
     ]
    },
    {
     "alias": "CAN",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ingate_value",
     "query": "SELECT count(\"value\") FROM \"autogen\".\"ingate_value\" WHERE (\"host\" =~ /^$devname$/ AND \"instance\" = 'sip-message' AND \"type\" = 'count' AND \"type_instance\" = 'INVITE-RX') AND $timeFilter GROUP BY time(24h) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "24h" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$devname$/" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "sip-message" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "count" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "CANCEL-TX" }
     ]
    },
    {
     "alias": "INF",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ingate_value",
     "query": "SELECT count(\"value\") FROM \"autogen\".\"ingate_value\" WHERE (\"host\" =~ /^$devname$/ AND \"instance\" = 'sip-message' AND \"type\" = 'count' AND \"type_instance\" = 'INVITE-RX') AND $timeFilter GROUP BY time(24h) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "24h" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$devname$/" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "sip-message" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "count" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "INFO-TX" }
     ]
    },
    {
     "alias": "INV",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ingate_value",
     "query": "SELECT count(\"value\") FROM \"autogen\".\"ingate_value\" WHERE (\"host\" =~ /^$devname$/ AND \"instance\" = 'sip-message' AND \"type\" = 'count' AND \"type_instance\" = 'INVITE-RX') AND $timeFilter GROUP BY time(24h) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "24h" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$devname$/" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "sip-message" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "count" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "INVITE-TX" }
     ]
    },
    {
     "alias": "MSG",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ingate_value",
     "query": "SELECT count(\"value\") FROM \"autogen\".\"ingate_value\" WHERE (\"host\" =~ /^$devname$/ AND \"instance\" = 'sip-message' AND \"type\" = 'count' AND \"type_instance\" = 'INVITE-RX') AND $timeFilter GROUP BY time(24h) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "24h" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$devname$/" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "sip-message" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "count" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "MESSAGE-TX" }
     ]
    },
    {
     "alias": "MSG",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ingate_value",
     "query": "SELECT count(\"value\") FROM \"autogen\".\"ingate_value\" WHERE (\"host\" =~ /^$devname$/ AND \"instance\" = 'sip-message' AND \"type\" = 'count' AND \"type_instance\" = 'INVITE-RX') AND $timeFilter GROUP BY time(24h) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "24h" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$devname$/" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "sip-message" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "count" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "NOTIFY-TX" }
     ]
    },
    {
     "alias": "OPT",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ingate_value",
     "query": "SELECT count(\"value\") FROM \"autogen\".\"ingate_value\" WHERE (\"host\" =~ /^$devname$/ AND \"instance\" = 'sip-message' AND \"type\" = 'count' AND \"type_instance\" = 'INVITE-RX') AND $timeFilter GROUP BY time(24h) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "24h" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$devname$/" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "sip-message" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "count" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "OPTIONS-TX" }
     ]
    },
    {
     "alias": "PRK",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ingate_value",
     "query": "SELECT count(\"value\") FROM \"autogen\".\"ingate_value\" WHERE (\"host\" =~ /^$devname$/ AND \"instance\" = 'sip-message' AND \"type\" = 'count' AND \"type_instance\" = 'INVITE-RX') AND $timeFilter GROUP BY time(24h) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "24h" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$devname$/" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "sip-message" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "count" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "PRACK-TX" }
     ]
    },
    {
     "alias": "PUB",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ingate_value",
     "query": "SELECT count(\"value\") FROM \"autogen\".\"ingate_value\" WHERE (\"host\" =~ /^$devname$/ AND \"instance\" = 'sip-message' AND \"type\" = 'count' AND \"type_instance\" = 'INVITE-RX') AND $timeFilter GROUP BY time(24h) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "24h" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$devname$/" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "sip-message" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "count" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "PUBLISH-TX" }
     ]
    },
    {
     "alias": "REF",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ingate_value",
     "query": "SELECT count(\"value\") FROM \"autogen\".\"ingate_value\" WHERE (\"host\" =~ /^$devname$/ AND \"instance\" = 'sip-message' AND \"type\" = 'count' AND \"type_instance\" = 'INVITE-RX') AND $timeFilter GROUP BY time(24h) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "24h" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$devname$/" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "sip-message" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "count" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "REFER-TX" }
     ]
    },
    {
     "alias": "REG",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ingate_value",
     "query": "SELECT count(\"value\") FROM \"autogen\".\"ingate_value\" WHERE (\"host\" =~ /^$devname$/ AND \"instance\" = 'sip-message' AND \"type\" = 'count' AND \"type_instance\" = 'INVITE-RX') AND $timeFilter GROUP BY time(24h) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "24h" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$devname$/" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "sip-message" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "count" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "REGISTER-TX" }
     ]
    },
    {
     "alias": "SUB",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ingate_value",
     "query": "SELECT count(\"value\") FROM \"autogen\".\"ingate_value\" WHERE (\"host\" =~ /^$devname$/ AND \"instance\" = 'sip-message' AND \"type\" = 'count' AND \"type_instance\" = 'INVITE-RX') AND $timeFilter GROUP BY time(24h) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "24h" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$devname$/" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "sip-message" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "count" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "SUBSCRIBE-TX" }
     ]
    },
    {
     "alias": "UNK",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ingate_value",
     "query": "SELECT count(\"value\") FROM \"autogen\".\"ingate_value\" WHERE (\"host\" =~ /^$devname$/ AND \"instance\" = 'sip-message' AND \"type\" = 'count' AND \"type_instance\" = 'INVITE-RX') AND $timeFilter GROUP BY time(24h) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "24h" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$devname$/" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "sip-message" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "count" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "UNKNOWN-TX" }
     ]
    }
   ]
  },
  {
   "title": "Ingress Method Counters",
   "type": "bargauge",
   "description": "Shows the current running total for SIP method types received",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 54 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "ACK",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ingate_value",
     "query": "SELECT last(\"value\") FROM \"autogen\".\"ingate_value\" WHERE (\"host\" =~ /^$devname$/ AND \"instance\" = 'sip-message' AND \"type\" = 'count' AND \"type_instance\" = 'ACK-RX') AND $timeFilter GROUP BY time($__interval) fill(none)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$devname$/" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "sip-message" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "count" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "ACK-RX" }
     ]
    },
    {
     "alias": "BYE",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ingate_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$devname$/" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "sip-message" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "count" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "BYE-RX" }
     ]
    },
    {
     "alias": "CAN",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ingate_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$devname$/" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "sip-message" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "count" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "CANCEL-RX" }
     ]
    },
    {
     "alias": "INF",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ingate_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$devname$/" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "sip-message" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "count" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "INFO-RX" }
     ]
    },
    {
     "alias": "INV",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ingate_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$devname$/" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "sip-message" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "count" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "INVITE-RX" }
     ]
    },
    {
     "alias": "MSG",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ingate_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$devname$/" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "sip-message" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "count" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "MESSAGE-RX" }
     ]
    },
    {
     "alias": "OPT",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ingate_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$devname$/" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "sip-message" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "count" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "OPTIONS-RX" }
     ]
    },
    {
     "alias": "PRK",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ingate_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$devname$/" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "sip-message" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "count" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "PRACK-RX" }
     ]
    },
    {
     "alias": "PUB",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ingate_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$devname$/" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "sip-message" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "count" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "PUBLISH-RX" }
     ]
    },
    {
     "alias": "REF",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ingate_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$devname$/" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "sip-message" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "count" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "REFER-RX" }
     ]
    },
    {
     "alias": "REG",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ingate_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$devname$/" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "sip-message" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "count" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "REGISTER-RX" }
     ]
    },
    {
     "alias": "SUB",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ingate_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$devname$/" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "sip-message" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "count" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "SUBSCRIBE-RX" }
     ]
    },
    {
     "alias": "other",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ingate_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$devname$/" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "sip-message" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "count" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "UNKNOWN-RX" }
     ]
    }
   ]
  },
  {
   "title": "Egress Method Counters",
   "type": "bargauge",
   "description": "Shows the current running total for SIP method types sent",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 54 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "ACK",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ingate_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$devname$/" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "sip-message" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "count" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "ACK-TX" }
     ]
    },
    {
     "alias": "BYE",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ingate_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$devname$/" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "sip-message" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "count" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "BYE-TX" }
     ]
    },
    {
     "alias": "CAN",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ingate_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$devname$/" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "sip-message" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "count" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "CANCEL-TX" }
     ]
    },
    {
     "alias": "INF",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ingate_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$devname$/" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "sip-message" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "count" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "INFO-TX" }
     ]
    },
    {
     "alias": "INV",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ingate_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$devname$/" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "sip-message" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "count" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "INVITE-TX" }
     ]
    },
    {
     "alias": "MSG",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ingate_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$devname$/" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "sip-message" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "count" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "MESSAGE-TX" }
     ]
    },
    {
     "alias": "OPT",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ingate_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$devname$/" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "sip-message" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "count" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "OPTIONS-TX" }
     ]
    },
    {
     "alias": "PRK",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ingate_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$devname$/" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "sip-message" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "count" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "PRACK-TX" }
     ]
    },
    {
     "alias": "PUB",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ingate_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$devname$/" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "sip-message" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "count" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "PUBLISH-TX" }
     ]
    },
    {
     "alias": "REF",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ingate_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$devname$/" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "sip-message" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "count" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "REFER-TX" }
     ]
    },
    {
     "alias": "REG",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ingate_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$devname$/" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "sip-message" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "count" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "REGISTER-TX" }
     ]
    },
    {
     "alias": "SUB",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ingate_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$devname$/" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "sip-message" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "count" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "SUBSCRIBE-TX" }
     ]
    },
    {
     "alias": "other",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ingate_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$devname$/" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "sip-message" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "count" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "UNKNOWN-TX" }
     ]
    }
   ]
  },
  {
   "title": "Egress Response Counters",
   "type": "bargauge",
   "description": "Shows the current running total for SIP response classes sent",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 59 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "1xx",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ingate_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$devname$/" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "sip-message" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "count" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "1XX-TX" }
     ]
    },
    {
     "alias": "2xx",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ingate_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$devname$/" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "sip-message" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "count" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "2XX-TX" }
     ]
    },
    {
     "alias": "3xx",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ingate_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$devname$/" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "sip-message" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "count" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "3XX-TX" }
     ]
    },
    {
     "alias": "4xx",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ingate_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$devname$/" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "sip-message" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "count" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "4XX-TX" }
     ]
    },
    {
     "alias": "5xx",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ingate_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$devname$/" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "sip-message" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "count" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "5XX-TX" }
     ]
    },
    {
     "alias": "6xx",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ingate_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$devname$/" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "sip-message" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "count" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "6XX-TX" }
     ]
    }
   ]
  },
  {
   "title": "Ingress Response Counters",
   "type": "bargauge",
   "description": "Shows the current running total for SIP response classes received",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 59 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "1xx",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ingate_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$devname$/" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "sip-message" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "count" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "1XX-RX" }
     ]
    },
    {
     "alias": "2xx",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ingate_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$devname$/" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "sip-message" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "count" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "2XX-RX" }
     ]
    },
    {
     "alias": "3xx",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ingate_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$devname$/" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "sip-message" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "count" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "3XX-RX" }
     ]
    },
    {
     "alias": "4xx",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ingate_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$devname$/" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "sip-message" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "count" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "4XX-RX" }
     ]
    },
    {
     "alias": "5xx",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ingate_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$devname$/" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "sip-message" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "count" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "5XX-RX" }
     ]
    },
    {
     "alias": "6xx",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ingate_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$devname$/" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "sip-message" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "count" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "6XX-RX" }
     ]
    }
   ]
  },
  {
   "title": "SIP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Ingress SIP method rates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "ACK",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ingate_value",
     "query": "SELECT derivative(last(\"value\"), 10s) FROM \"ingate_value\" WHERE (\"instance\" = 'sip-message' AND \"type_instance\" = 'ACK-RX' AND \"host\" =~ /^$devname$/) AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "sip-message" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "ACK-RX" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$devname$/" }
     ]
    },
    {
     "alias": "BYE",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ingate_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "sip-message" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "BYE-RX" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$devname$/" }
     ]
    },
    {
     "alias": "CAN",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ingate_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "sip-message" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "CANCEL-RX" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$devname$/" }
     ]
    },
    {
     "alias": "INF",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ingate_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "sip-message" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "INFO-RX" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$devname$/" }
     ]
    },
    {
     "alias": "INV",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ingate_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "sip-message" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "INVITE-RX" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$devname$/" }
     ]
    },
    {
     "alias": "MSG",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ingate_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "sip-message" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "MESSAGE-RX" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$devname$/" }
     ]
    },
    {
     "alias": "NTF",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ingate_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "sip-message" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "NOTIFY-RX" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$devname$/" }
     ]
    },
    {
     "alias": "OPT",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ingate_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "sip-message" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "OPTIONS-RX" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$devname$/" }
     ]
    },
    {
     "alias": "PRK",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ingate_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "sip-message" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "PRACK-RX" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$devname$/" }
     ]
    },
    {
     "alias": "PUB",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ingate_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "sip-message" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "PUBLISH-RX" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$devname$/" }
     ]
    },
    {
     "alias": "REF",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ingate_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "sip-message" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "REFER-RX" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$devname$/" }
     ]
    },
    {
     "alias": "REG",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ingate_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "sip-message" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "REGISTER-RX" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$devname$/" }
     ]
    },
    {
     "alias": "SUB",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ingate_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "sip-message" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "SUBSCRIBE-RX" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$devname$/" }
     ]
    },
    {
     "alias": "other",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ingate_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "sip-message" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "UNKNOWN-RX" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$devname$/" }
     ]
    }
   ]
  },
  {
   "title": "Egress SIP method rates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "ACK",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ingate_value",
     "query": "SELECT derivative(sum(\"value\"), 10s) FROM \"ingate_tx\" WHERE (\"instance\" = 'sip-message' AND \"type_instance\" = 'ACK' AND \"host\" =~ /^$devname$/) AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "sip-message" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "ACK-TX" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$devname$/" }
     ]
    },
    {
     "alias": "BYE",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ingate_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "sip-message" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "BYE-TX" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$devname$/" }
     ]
    },
    {
     "alias": "CAN",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ingate_value",
     "query": "SELECT derivative(last(\"value\"), 10s) FROM \"ingate_tx\" WHERE (\"instance\" = 'sip-message' AND \"type_instance\" = 'CANCEL' AND \"host\" =~ /^$devname$/) AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "sip-message" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "CANCEL-TX" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$devname$/" }
     ]
    },
    {
     "alias": "INF",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ingate_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "sip-message" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "INFO-TX" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$devname$/" }
     ]
    },
    {
     "alias": "INV",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ingate_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "sip-message" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "INVITE-TX" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$devname$/" }
     ]
    },
    {
     "alias": "MSG",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ingate_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "sip-message" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "MESSAGE-TX" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$devname$/" }
     ]
    },
    {
     "alias": "NTF",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ingate_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "sip-message" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "NOTIFY-TX" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$devname$/" }
     ]
    },
    {
     "alias": "OPT",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "ingate_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "sip-message" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "OPTIONS-TX" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$devname$/" }
     ]
    },
    {
     "alias": "PRK",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ingate_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "sip-message" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "PRACK-TX" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$devname$/" }
     ]
    },
    {
     "alias": "PUB",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ingate_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "sip-message" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "PUBLISH-TX" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$devname$/" }
     ]
    },
    {
     "alias": "REF",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ingate_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "sip-message" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "REFER-TX" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$devname$/" }
     ]
    },
    {
     "alias": "REG",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ingate_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "sip-message" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "REGISTER-TX" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$devname$/" }
     ]
    },
    {
     "alias": "SUB",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ingate_value",
     "query": "SELECT derivative(mean(\"value\"), 10s) FROM \"ingate_value\" WHERE (\"instance\" = 'sip-message' AND \"type_instance\" = 'SUBSCRIBE-TX' AND \"host\" =~ /^$devname$/) AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "sip-message" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "SUBSCRIBE-TX" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$devname$/" }
     ]
    },
    {
     "alias": "other",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ingate_value",
     "query": "SELECT derivative(mean(\"value\"), 10s) FROM \"ingate_value\" WHERE (\"instance\" = 'sip-message' AND \"type_instance\" = 'SUBSCRIBE-TX' AND \"host\" =~ /^$devname$/) AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "sip-message" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "UNKNOWN-TX" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$devname$/" }
     ]
    }
   ]
  },
  {
   "title": "Egress SIP response rates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "1XX",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ingate_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "sip-message" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "1XX-TX" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$devname$/" }
     ]
    },
    {
     "alias": "2XX",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ingate_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "sip-message" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "2XX-TX" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$devname$/" }
     ]
    },
    {
     "alias": "3XX",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ingate_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "sip-message" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "3XX-TX" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$devname$/" }
     ]
    },
    {
     "alias": "4XX",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ingate_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "sip-message" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "4XX-TX" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$devname$/" }
     ]
    },
    {
     "alias": "5XX",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ingate_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "sip-message" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "5XX-TX" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$devname$/" }
     ]
    },
    {
     "alias": "6XX",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ingate_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "sip-message" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "6XX-TX" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$devname$/" }
     ]
    }
   ]
  },
  {
   "title": "Ingress SIP response rates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "1XX",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ingate_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "sip-message" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "1XX-RX" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$devname$/" }
     ]
    },
    {
     "alias": "2XX",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ingate_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "sip-message" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "2XX-RX" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$devname$/" }
     ]
    },
    {
     "alias": "3XX",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ingate_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "sip-message" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "3XX-RX" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$devname$/" }
     ]
    },
    {
     "alias": "4XX",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ingate_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "sip-message" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "4XX-RX" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$devname$/" }
     ]
    },
    {
     "alias": "5XX",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ingate_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "sip-message" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "5XX-RX" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$devname$/" }
     ]
    },
    {
     "alias": "6XX",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ingate_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "sip-message" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "6XX-RX" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$devname$/" }
     ]
    }
   ]
  },
  {
   "title": "SIP Licenses (in use)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "(Concurrent) CCS",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ingate_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$devname$/" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "sip-license" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "CCS" }
     ]
    },
    {
     "alias": "(Remote) RUS",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ingate_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$devname$/" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "sip-license" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "RUS" }
     ]
    },
    {
     "alias": "(Registrar) SRU",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ingate_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$devname$/" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "sip-license" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "SRU" }
     ]
    }
   ]
  },
  {
   "title": "SIP Status",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "REG",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ingate_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "sip-status" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "REGISTRATIONS" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$devname$/" }
     ]
    },
    {
     "alias": "Max Reg",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ingate_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "sip-status" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "REGISTRATIONS_MAX" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$devname$/" }
     ]
    },
    {
     "alias": "Max Calls",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ingate_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "sip-status" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "CALLS_MAX" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$devname$/" }
     ]
    },
    {
     "alias": "Calls",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ingate_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "sip-status" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "CALLS" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$devname$/" }
     ]
    },
    {
     "alias": "Calling",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ingate_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "sip-status" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "CALLING" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$devname$/" }
     ]
    }
   ]
  },
  {
   "title": "SIP License Usage (rate)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "(Concurrent) CCS aka CSPS Call setups/sec",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ingate_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ "10s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "sip-license" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "CCS" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$devname$/" }
     ]
    },
    {
     "alias": "(Remote) RUS",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ingate_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ "10s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "sip-license" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "RUS" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$devname$/" }
     ]
    },
    {
     "alias": "(Registrar) SRU",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ingate_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ "10s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "sip-license" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "SRU" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$devname$/" }
     ]
    }
   ]
  },
  {
   "title": "SIP Status (rate)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "REG Max",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ingate_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "sip-status" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "REGISTRATIONS_MAX" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$devname$/" }
     ]
    },
    {
     "alias": "REG",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ingate_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "sip-status" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "REGISTRATIONS" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$devname$/" }
     ]
    },
    {
     "alias": "Calls",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ingate_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "sip-status" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "CALLS" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$devname$/" }
     ]
    },
    {
     "alias": "Calling",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ingate_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "sip-status" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "CALLING" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$devname$/" }
     ]
    },
    {
     "alias": "Calls Max",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ingate_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "sip-status" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "CALLS_MAX" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$devname$/" }
     ]
    }
   ]
  }
 ]
}