{
 "title": "Ingate SIP stats - Prometheus based",
 "description": "Stats panel for Ingate SBCs - for Prometheus back-end",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(ingatesys_cpu_total, job)"
   },
   {
    "name": "hostnameip",
    "label": "Host:",
    "query": "label_values(ingatesys_cpu_total{job=~\"$job\"},instance)"
   },
   {
    "name": "unit_id",
    "label": "ID:",
    "query": "label_values(ingatesys_cpu_total{instance=\"$hostnameip\"}, exported_instance)"
   },
   {
    "name": "eth",
    "label": "Eth:",
    "query": "label_values(ingatesys_interface_if_dropped_rx_total{instance=~\"$hostnameip\"}, interface)"
   },
   {
    "name": "node",
    "label": "Host:",
    "query": "label_values(ingatesys_cpu_total{job=\"$job\",instance=\"$hostnameip\"}, instance)"
   },
   {
    "name": "port",
    "label": "Port",
    "query": "label_values(ingatesys_cpu_total{instance=~\"$node:(.*)\"}, instance)"
   },
   {
    "name": "cpu_value",
    "label": "CPU:",
    "query": "label_values(ingatesys_cpu_total{instance=\"$hostnameip\"}, cpu)"
   }
  ]
 },
 "panels": [
  {
   "title": "Host Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Memory Usage on $unit_id",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": " ingatesys_memory{instance=~\"$hostnameip\",job=~\"$job\", memory=\"used\" }",
       "legendFormat": "Used"
      },
      {
       "expr": "ingatesys_memory{instance=~\"$hostnameip\",job=~\"$job\",memory=\"slab_unrecl\" }",
       "legendFormat": "Slab Unrecl"
      },
      {
       "expr": "ingatesys_memory{instance=~\"$hostnameip\",job=~\"$job\", memory=\"slab_recl\" }",
       "legendFormat": "Slab Recl"
      },
      {
       "expr": "ingatesys_memory{instance=~\"$hostnameip\",job=~\"$job\", memory=\"buffered\" }",
       "legendFormat": "Buffered"
      },
      {
       "expr": "ingatesys_memory{instance=~\"$hostnameip\",job=~\"$job\", memory=\"cached\" }",
       "legendFormat": "Cached"
      },
      {
       "expr": " ingatesys_memory{instance=~\"$hostnameip\",job=~\"$job\", memory=\"free\" }",
       "legendFormat": "Free"
      }
     ]
    }
   ]
  },
  {
   "title": "Host Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "$eth octets/sec on $unit_id",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 2 },
     "repeat": "eth",
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(ingatesys_interface_if_octets_rx_total{instance=~\"$hostnameip\",interface=~\"$eth\"}[$__rate_interval])",
       "legendFormat": "Rx"
      },
      {
       "expr": "rate(ingatesys_interface_if_octets_tx_total{instance=~\"$hostnameip\",interface=~\"$eth\"}[$__rate_interval])",
       "legendFormat": "Tx"
      }
     ]
    },
    {
     "title": "$eth packets/sec on $unit_id",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
     "repeat": "eth",
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "rate(ingatesys_interface_if_packets_rx_total{instance=~\"$hostnameip\",interface=~\"$eth\"}[$__rate_interval])",
       "legendFormat": "Rx"
      },
      {
       "expr": "rate(ingatesys_interface_if_packets_tx_total{instance=~\"$hostnameip\",interface=~\"$eth\"}[$__rate_interval])",
       "legendFormat": "Tx"
      },
      {
       "expr": "rate(ingatesys_interface_if_dropped_rx_total{instance=~\"$hostnameip\",interface=~\"$eth\"}[$__rate_interval])",
       "legendFormat": "Drop Rx"
      },
      {
       "expr": "rate(ingatesys_interface_if_errors_rx_total{instance=~\"$hostnameip\",interface=~\"$eth\"}[$__rate_interval])",
       "legendFormat": "Err Rx"
      }
     ]
    }
   ]
  },
  {
   "title": "Host CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "System Load on $unit_id",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 23, "x": 1, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(ingatesys_load_shortterm{instance=~\"$hostnameip\"}[$__rate_interval])",
       "legendFormat": "1m"
      },
      {
       "expr": "rate(ingatesys_load_midterm{instance=~\"$hostnameip\"}[$__rate_interval])",
       "legendFormat": "5m"
      },
      {
       "expr": "rate(ingatesys_load_longterm{instance=~\"$hostnameip\"}[$__rate_interval])",
       "legendFormat": "15m"
      }
     ]
    },
    {
     "title": "CPU ($cpu_value) usage on $unit_id",
     "type": "graph",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 12 },
     "repeat": "cpu_value",
     "yaxes": [
      { "format": "percent", "label": "Jiffies" }
     ],
     "targets": [
      {
       "expr": "rate(ingatesys_cpu_total{instance=~\"$hostnameip\",cpu=~\"$cpu_value\",type=\"steal\"}[$__rate_interval])",
       "legendFormat": "Steal"
      },
      {
       "expr": "rate(ingatesys_cpu_total{instance=~\"$hostnameip\",cpu=~\"$cpu_value\",type=\"softirq\"}[$__rate_interval])",
       "legendFormat": "IRQ"
      },
      {
       "expr": "rate(ingatesys_cpu_total{instance=~\"$hostnameip\",cpu=~\"$cpu_value\",type=\"system\"}[$__rate_interval])",
       "legendFormat": "Sys"
      },
      {
       "expr": "rate(ingatesys_cpu_total{instance=~\"$hostnameip\",cpu=~\"$cpu_value\",type=\"interrupt\"}[$__rate_interval])",
       "legendFormat": "Int"
      },
      {
       "expr": "rate(ingatesys_cpu_total{instance=~\"$hostnameip\",cpu=~\"$cpu_value\",type=\"wait\"}[$__rate_interval])",
       "legendFormat": "Wait"
      },
      {
       "expr": "rate(ingatesys_cpu_total{instance=~\"$hostnameip\",cpu=~\"$cpu_value\",type=\"user\"}[$__rate_interval])",
       "legendFormat": "User"
      },
      {
       "expr": "rate(ingatesys_cpu_total{instance=~\"$hostnameip\",cpu=~\"$cpu_value\",type=\"nice\"}[$__rate_interval])",
       "legendFormat": "Nice"
      },
      {
       "expr": "rate(ingatesys_cpu_total{instance=~\"$hostnameip\",cpu=~\"$cpu_value\", type=\"idle\"}[$__rate_interval])",
       "legendFormat": "Idle"
      }
     ]
    }
   ]
  },
  {
   "title": "SIP Counters",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Ingress Method Counters",
     "type": "bargauge",
     "description": "Shows the current running total for SIP method types received",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "ingatesys_ingate_count{instance=~\"$hostnameip\",type=\"ACK-RX\"}",
       "legendFormat": "ACK"
      },
      {
       "expr": "ingatesys_ingate_count{instance=~\"$hostnameip\",type=\"BYE-RX\"}",
       "legendFormat": "BYE"
      },
      {
       "expr": "ingatesys_ingate_count{instance=~\"$hostnameip\",type=\"CANCEL-RX\"}",
       "legendFormat": "CAN"
      },
      {
       "expr": "ingatesys_ingate_count{instance=~\"$hostnameip\",type=\"INFO-RX\"}",
       "legendFormat": "INF"
      },
      {
       "expr": "ingatesys_ingate_count{instance=~\"$hostnameip\",type=\"INVITE-RX\"}",
       "legendFormat": "INV"
      },
      {
       "expr": "ingatesys_ingate_count{instance=~\"$hostnameip\",type=\"MESSAGE-RX\"}",
       "legendFormat": "MSG"
      },
      {
       "expr": "ingatesys_ingate_count{instance=~\"$hostnameip\",type=\"NOTIFY-RX\"}",
       "legendFormat": "NFY"
      },
      {
       "expr": "ingatesys_ingate_count{instance=~\"$hostnameip\",type=\"OPTIONS-RX\"}",
       "legendFormat": "OPT"
      },
      {
       "expr": "ingatesys_ingate_count{instance=~\"$hostnameip\",type=\"PRACK-RX\"}",
       "legendFormat": "PRK"
      },
      {
       "expr": "ingatesys_ingate_count{instance=~\"$hostnameip\",type=\"PUBLISH-RX\"}",
       "legendFormat": "PUB"
      },
      {
       "expr": "ingatesys_ingate_count{instance=~\"$hostnameip\",type=\"REFER-RX\"}",
       "legendFormat": "REF"
      },
      {
       "expr": "ingatesys_ingate_count{instance=~\"$hostnameip\",type=\"REGISTER-RX\"}",
       "legendFormat": "REG"
      },
      {
       "expr": "ingatesys_ingate_count{instance=~\"$hostnameip\",type=\"SUBSCRIBE-RX\"}",
       "legendFormat": "SUB"
      },
      {
       "expr": "ingatesys_ingate_count{instance=~\"$hostnameip\",type=\"UNKNOWN-RX\"}",
       "legendFormat": "?"
      }
     ]
    },
    {
     "title": "Egress Method Counters",
     "type": "bargauge",
     "description": "Shows the current running total for SIP method types sent",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "ingatesys_ingate_count{instance=~\"$hostnameip\",type=\"ACK-TX\"}",
       "legendFormat": "ACK"
      },
      {
       "expr": "ingatesys_ingate_count{instance=~\"$hostnameip\",type=\"BYE-TX\"}",
       "legendFormat": "BYE"
      },
      {
       "expr": "ingatesys_ingate_count{instance=~\"$hostnameip\",type=\"CANCEL-TX\"}",
       "legendFormat": "CAN"
      },
      {
       "expr": "ingatesys_ingate_count{instance=~\"$hostnameip\",type=\"INFO-TX\"}",
       "legendFormat": "INF"
      },
      {
       "expr": "ingatesys_ingate_count{instance=~\"$hostnameip\",type=\"INVITE-TX\"}",
       "legendFormat": "INV"
      },
      {
       "expr": "ingatesys_ingate_count{instance=~\"$hostnameip\",type=\"MESSAGE-TX\"}",
       "legendFormat": "MSG"
      },
      {
       "expr": "ingatesys_ingate_count{instance=~\"$hostnameip\",type=\"NOTIFY-TX\"}",
       "legendFormat": "NFY"
      },
      {
       "expr": "ingatesys_ingate_count{instance=~\"$hostnameip\",type=\"OPTIONS-TX\"}",
       "legendFormat": "OPT"
      },
      {
       "expr": "ingatesys_ingate_count{instance=~\"$hostnameip\",type=\"PRACK-TX\"}",
       "legendFormat": "PRK"
      },
      {
       "expr": "ingatesys_ingate_count{instance=~\"$hostnameip\",type=\"PUBLISH-TX\"}",
       "legendFormat": "PUB"
      },
      {
       "expr": "ingatesys_ingate_count{instance=~\"$hostnameip\",type=\"REFER-TX\"}",
       "legendFormat": "REF"
      },
      {
       "expr": "ingatesys_ingate_count{instance=~\"$hostnameip\",type=\"REGISTER-TX\"}",
       "legendFormat": "REG"
      },
      {
       "expr": "ingatesys_ingate_count{instance=~\"$hostnameip\",type=\"SUBSCRIBE-TX\"}",
       "legendFormat": "SUB"
      },
      {
       "expr": "ingatesys_ingate_count{instance=~\"$hostnameip\",type=\"UNKNOWN-TX\"}",
       "legendFormat": "?"
      }
     ]
    },
    {
     "title": "Egress Response Counters",
     "type": "bargauge",
     "description": "Shows the current running total for SIP response classes sent",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "ingatesys_ingate_count{instance=~\"$hostnameip\",type=\"1XX-TX\"}",
       "legendFormat": "1XX"
      },
      {
       "expr": "ingatesys_ingate_count{instance=~\"$hostnameip\",type=\"2XX-TX\"}",
       "legendFormat": "2XX"
      },
      {
       "expr": "ingatesys_ingate_count{instance=~\"$hostnameip\",type=\"3XX-TX\"}",
       "legendFormat": "3XX"
      },
      {
       "expr": "ingatesys_ingate_count{instance=~\"$hostnameip\",type=\"4XX-TX\"}",
       "legendFormat": "4XX"
      },
      {
       "expr": "ingatesys_ingate_count{instance=~\"$hostnameip\",type=\"5XX-TX\"}",
       "legendFormat": "5XX"
      },
      {
       "expr": "ingatesys_ingate_count{instance=~\"$hostnameip\",type=\"6XX-TX\"}",
       "legendFormat": "6XX"
      }
     ]
    },
    {
     "title": "Ingress Response Counters",
     "type": "bargauge",
     "description": "Shows the current running total for SIP response classes received",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "ingatesys_ingate_count{instance=~\"$hostnameip\",type=\"1XX-RX\"}",
       "legendFormat": "1XX"
      },
      {
       "expr": "ingatesys_ingate_count{instance=~\"$hostnameip\",type=\"2XX-RX\"}",
       "legendFormat": "2XX"
      },
      {
       "expr": "ingatesys_ingate_count{instance=~\"$hostnameip\",type=\"3XX-RX\"}",
       "legendFormat": "3XX"
      },
      {
       "expr": "ingatesys_ingate_count{instance=~\"$hostnameip\",type=\"4XX-RX\"}",
       "legendFormat": "4XX"
      },
      {
       "expr": "ingatesys_ingate_count{instance=~\"$hostnameip\",type=\"5XX-RX\"}",
       "legendFormat": "5XX"
      },
      {
       "expr": "ingatesys_ingate_count{instance=~\"$hostnameip\",type=\"6XX-RX\"}",
       "legendFormat": "6XX"
      }
     ]
    }
   ]
  },
  {
   "title": "SIP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Ingress SIP method rates",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(ingatesys_ingate_count{instance=~\"$hostnameip\",type=\"ACK-RX\"}[$__rate_interval])",
       "legendFormat": "ACK"
      },
      {
       "expr": "rate(ingatesys_ingate_count{instance=~\"$hostnameip\",type=\"BYE-RX\"}[$__rate_interval])",
       "legendFormat": "BYE"
      },
      {
       "expr": "rate(ingatesys_ingate_count{instance=~\"$hostnameip\",type=\"CANCEL-RX\"}[$__rate_interval])",
       "legendFormat": "CAN"
      },
      {
       "expr": "rate(ingatesys_ingate_count{instance=~\"$hostnameip\",type=\"INFO-RX\"}[$__rate_interval])",
       "legendFormat": "INF"
      },
      {
       "expr": "rate(ingatesys_ingate_count{instance=~\"$hostnameip\",type=\"INVITE-RX\"}[$__rate_interval])",
       "legendFormat": "INV"
      },
      {
       "expr": "rate(ingatesys_ingate_count{instance=~\"$hostnameip\",type=\"MESSAGE-RX\"}[$__rate_interval])",
       "legendFormat": "MSG"
      },
      {
       "expr": "rate(ingatesys_ingate_count{instance=~\"$hostnameip\",type=\"NOTIFY-RX\"}[$__rate_interval])",
       "legendFormat": "NTF"
      },
      {
       "expr": "rate(ingatesys_ingate_count{instance=~\"$hostnameip\",type=\"OPTIONS-RX\"}[$__rate_interval])",
       "legendFormat": "OPT"
      },
      {
       "expr": "rate(ingatesys_ingate_count{instance=~\"$hostnameip\",type=\"PRACK-RX\"}[$__rate_interval])",
       "legendFormat": "PRK"
      },
      {
       "expr": "rate(ingatesys_ingate_count{instance=~\"$hostnameip\",type=\"PUBLISH-RX\"}[$__rate_interval])",
       "legendFormat": "PUB"
      },
      {
       "expr": "rate(ingatesys_ingate_count{instance=~\"$hostnameip\",type=\"REFER-RX\"}[$__rate_interval])",
       "legendFormat": "RFR"
      },
      {
       "expr": "rate(ingatesys_ingate_count{instance=~\"$hostnameip\",type=\"REGISTER-RX\"}[$__rate_interval])",
       "legendFormat": "REG"
      },
      {
       "expr": "rate(ingatesys_ingate_count{instance=~\"$hostnameip\",type=\"SUBSCRIBE-RX\"}[$__rate_interval])",
       "legendFormat": "SUB"
      },
      {
       "expr": "rate(ingatesys_ingate_count{instance=~\"$hostnameip\",type=\"UPDATE-RX\"}[$__rate_interval])",
       "legendFormat": "UPD"
      },
      {
       "expr": "rate(ingatesys_ingate_count{instance=~\"$hostnameip\",type=\"UNKNOWN-RX\"}[$__rate_interval])",
       "legendFormat": "?"
      }
     ]
    },
    {
     "title": "Egress SIP method rates",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(ingatesys_ingate_count{instance=~\"$hostnameip\",type=\"ACK-TX\"}[$__rate_interval])",
       "legendFormat": "ACK"
      },
      {
       "expr": "rate(ingatesys_ingate_count{instance=~\"$hostnameip\",type=\"BYE-TX\"}[$__rate_interval])",
       "legendFormat": "BYE"
      },
      {
       "expr": "rate(ingatesys_ingate_count{instance=~\"$hostnameip\",type=\"CANCEL-TX\"}[$__rate_interval])",
       "legendFormat": "CAN"
      },
      {
       "expr": "rate(ingatesys_ingate_count{instance=~\"$hostnameip\",type=\"INFO-TX\"}[$__rate_interval])",
       "legendFormat": "INF"
      },
      {
       "expr": "rate(ingatesys_ingate_count{instance=~\"$hostnameip\",type=\"INVITE-TX\"}[$__rate_interval])",
       "legendFormat": "INV"
      },
      {
       "expr": "rate(ingatesys_ingate_count{instance=~\"$hostnameip\",type=\"MESSAGE-TX\"}[$__rate_interval])",
       "legendFormat": "MSG"
      },
      {
       "expr": "rate(ingatesys_ingate_count{instance=~\"$hostnameip\",type=\"NOTIFY-TX\"}[$__rate_interval])",
       "legendFormat": "NTF"
      },
      {
       "expr": "rate(ingatesys_ingate_count{instance=~\"$hostnameip\",type=\"OPTIONS-TX\"}[$__rate_interval])",
       "legendFormat": "OPT"
      },
      {
       "expr": "rate(ingatesys_ingate_count{instance=~\"$hostnameip\",type=\"PRACK-TX\"}[$__rate_interval])",
       "legendFormat": "PRK"
      },
      {
       "expr": "rate(ingatesys_ingate_count{instance=~\"$hostnameip\",type=\"PUBLISH-TX\"}[$__rate_interval])",
       "legendFormat": "PUB"
      },
      {
       "expr": "rate(ingatesys_ingate_count{instance=~\"$hostnameip\",type=\"REFER-TX\"}[$__rate_interval])",
       "legendFormat": "RFR"
      },
      {
       "expr": "rate(ingatesys_ingate_count{instance=~\"$hostnameip\",type=\"REGISTER-TX\"}[$__rate_interval])",
       "legendFormat": "REG"
      },
      {
       "expr": "rate(ingatesys_ingate_count{instance=~\"$hostnameip\",type=\"SUBSCRIBE-TX\"}[$__rate_interval])",
       "legendFormat": "SUB"
      },
      {
       "expr": "rate(ingatesys_ingate_count{instance=~\"$hostnameip\",type=\"UPDATE-TX\"}[$__rate_interval])",
       "legendFormat": "UPD"
      },
      {
       "expr": "rate(ingatesys_ingate_count{instance=~\"$hostnameip\",type=\"UNKNOWN-TX\"}[$__rate_interval])",
       "legendFormat": "?"
      }
     ]
    },
    {
     "title": "Egress SIP response rates",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(ingatesys_ingate_count{instance=~\"$hostnameip\",type=\"1XX-TX\"}[$__rate_interval])",
       "legendFormat": "1XX"
      },
      {
       "expr": "rate(ingatesys_ingate_count{instance=~\"$hostnameip\",type=\"2XX-TX\"}[$__rate_interval])",
       "legendFormat": "2XX"
      },
      {
       "expr": "rate(ingatesys_ingate_count{instance=~\"$hostnameip\",type=\"3XX-TX\"}[$__rate_interval])",
       "legendFormat": "3XX"
      },
      {
       "expr": "rate(ingatesys_ingate_count{instance=~\"$hostnameip\",type=\"4XX-TX\"}[$__rate_interval])",
       "legendFormat": "4XX"
      },
      {
       "expr": "rate(ingatesys_ingate_count{instance=~\"$hostnameip\",type=\"5XX-TX\"}[$__rate_interval])",
       "legendFormat": "5XX"
      },
      {
       "expr": "rate(ingatesys_ingate_count{instance=~\"$hostnameip\",type=\"6XX-TX\"}[$__rate_interval])",
       "legendFormat": "6XX"
      }
     ]
    },
    {
     "title": "Ingress SIP response rates",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(ingatesys_ingate_count{instance=~\"$hostnameip\",type=\"1XX-RX\"}[$__rate_interval])",
       "legendFormat": "1XX"
      },
      {
       "expr": "rate(ingatesys_ingate_count{instance=~\"$hostnameip\",type=\"2XX-RX\"}[$__rate_interval])",
       "legendFormat": "2XX"
      },
      {
       "expr": "rate(ingatesys_ingate_count{instance=~\"$hostnameip\",type=\"3XX-RX\"}[$__rate_interval])",
       "legendFormat": "3XX"
      },
      {
       "expr": "rate(ingatesys_ingate_count{instance=~\"$hostnameip\",type=\"4XX-RX\"}[$__rate_interval])",
       "legendFormat": "4XX"
      },
      {
       "expr": "rate(ingatesys_ingate_count{instance=~\"$hostnameip\",type=\"5XX-RX\"}[$__rate_interval])",
       "legendFormat": "5XX"
      },
      {
       "expr": "rate(ingatesys_ingate_count{instance=~\"$hostnameip\",type=\"6XX-RX\"}[$__rate_interval])",
       "legendFormat": "6XX"
      }
     ]
    },
    {
     "title": "SIP Licenses (in use)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "ingatesys_ingate_count{instance=~\"$hostnameip\",type=\"CCS\"}",
       "legendFormat": "(Concurrent) CCS"
      },
      {
       "expr": "ingatesys_ingate_count{instance=~\"$hostnameip\",type=\"CCS_MAX\"}",
       "legendFormat": "CCS Max"
      },
      {
       "expr": "ingatesys_ingate_count{instance=~\"$hostnameip\",type=\"RUS\"}",
       "legendFormat": "(Remote) RUS"
      },
      {
       "expr": "ingatesys_ingate_count{instance=~\"$hostnameip\",type=\"RUS_MAX\"}",
       "legendFormat": "RUS Max"
      },
      {
       "expr": "ingatesys_ingate_count{instance=~\"$hostnameip\",type=\"SRU\"}",
       "legendFormat": "(Registrar) SRU"
      },
      {
       "expr": "ingatesys_ingate_count{instance=~\"$hostnameip\",type=\"SRU_MAX\"}",
       "legendFormat": "SRU Max"
      }
     ]
    },
    {
     "title": "SIP Status",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "ingatesys_ingate_count{instance=~\"$hostnameip\",type=\"REGISTRATIONS\"}",
       "legendFormat": "Reg"
      },
      {
       "expr": "ingatesys_ingate_count{instance=~\"$hostnameip\",type=\"REGISTRATIONS_MAX\"}",
       "legendFormat": "Reg Max"
      },
      {
       "expr": "ingatesys_ingate_count{instance=~\"$hostnameip\",type=\"CALLS\"}",
       "legendFormat": "Calls"
      },
      {
       "expr": "ingatesys_ingate_count{instance=~\"$hostnameip\",type=\"CALLS_MAX\"}",
       "legendFormat": "Max Calls"
      },
      {
       "expr": "ingatesys_ingate_count{instance=~\"$hostnameip\",type=\"CALLING\"}",
       "legendFormat": "Calling"
      }
     ]
    },
    {
     "title": "SIP License Usage (rate)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(ingatesys_ingate_count{instance=~\"$hostnameip\",type=\"CCS\"}[$__rate_interval])",
       "legendFormat": "CCS"
      },
      {
       "expr": "rate(ingatesys_ingate_count{instance=~\"$hostnameip\",type=\"CCS_MAX\"}[$__rate_interval])",
       "legendFormat": "CCS Max"
      },
      {
       "expr": "rate(ingatesys_ingate_count{instance=~\"$hostnameip\",type=\"RUS\"}[$__rate_interval])",
       "legendFormat": "RUS"
      },
      {
       "expr": "rate(ingatesys_ingate_count{instance=~\"$hostnameip\",type=\"RUS_MAX\"}[$__rate_interval])",
       "legendFormat": "RUS Max"
      },
      {
       "expr": "rate(ingatesys_ingate_count{instance=~\"$hostnameip\",type=\"SRU\"}[$__rate_interval])",
       "legendFormat": "SRU"
      },
      {
       "expr": "rate(ingatesys_ingate_count{instance=~\"$hostnameip\",type=\"SRU_MAX\"}[$__rate_interval])",
       "legendFormat": "SRU Max"
      }
     ]
    },
    {
     "title": "SIP Status (rate)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(ingatesys_ingate_count{instance=~\"$hostnameip\",type=\"CALLS\"}[$__rate_interval])",
       "legendFormat": "Calls"
      },
      {
       "expr": "rate(ingatesys_ingate_count{instance=~\"$hostnameip\",type=\"CALLS_MAX\"}[$__rate_interval])",
       "legendFormat": "Max Calls"
      },
      {
       "expr": "rate(ingatesys_ingate_count{instance=~\"$hostnameip\",type=\"CALLING\"}[$__rate_interval])",
       "legendFormat": "Calling"
      },
      {
       "expr": "rate(ingatesys_ingate_count{instance=~\"$hostnameip\",type=\"REGISTRATIONS\"}[$__rate_interval])",
       "legendFormat": "Reg"
      },
      {
       "expr": "rate(ingatesys_ingate_count{instance=~\"$hostnameip\",type=\"REGISTRATIONS_MAX\"}[$__rate_interval])",
       "legendFormat": "Max Reg"
      }
     ]
    }
   ]
  }
 ]
}