{
 "title": "Ingate SIP stats - GraphiteDB based",
 "description": "Stats panel for Ingate SBCs - for GraphiteDB back-end",
 "tags": [
  "Ingate",
  "SBC"
 ],
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "devname", "label": "Device", "query": "ingate*" },
   { "name": "cpu", "label": "CPU", "query": "ingate_$devname.cpu*" },
   { "name": "interface", "label": "Interface", "query": "ingate_$devname.interface*" }
  ]
 },
 "panels": [
  {
   "title": "Host Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Memory Usage on $devname",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "target": "aliasByMetric(ingate_$devname.memory.memory-used)"
      },
      {
       "target": "aliasByMetric(ingate_$devname.memory.memory-slab_unrecl)"
      },
      {
       "target": "aliasByMetric(ingate_$devname.memory.memory-slab_recl)"
      },
      {
       "target": "aliasByMetric(ingate_$devname.memory.memory-buffered)"
      },
      {
       "target": "aliasByMetric(ingate_$devname.memory.memory-cached)"
      },
      {
       "target": "aliasByMetric(ingate_$devname.memory.memory-free)"
      }
     ]
    }
   ]
  },
  {
   "title": "Host Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "$interface octets/sec on $devname",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 2 },
     "repeat": "interface",
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "target": "aliasByMetric(ingate_$devname.interface-$interface.if_octets.rx)"
      },
      {
       "target": "aliasByMetric(ingate_$devname.interface-$interface.if_octets.tx)"
      }
     ]
    },
    {
     "title": "$interface packets/sec on $devname",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
     "repeat": "interface",
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "target": "aliasByMetric(ingate_$devname.interface-$interface.if_packets.rx)"
      },
      {
       "target": "aliasByMetric(ingate_$devname.interface-$interface.if_packets.tx)"
      },
      {
       "target": "alias(ingate_$devname.interface-$interface.if_dropped.rx, 'Dropped')"
      },
      {
       "target": "alias(ingate_$devname.interface-$interface.if_errors.tx, 'TxErr')"
      },
      {
       "target": "alias(ingate_$devname.interface-$interface.if_mcast.tx, 'TxMcast')"
      }
     ]
    }
   ]
  },
  {
   "title": "Host CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "System Load on $devname",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 23, "x": 1, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "target": "aliasByMetric(ingate_$devname.load.load.shortterm)"
      },
      {
       "target": "aliasByMetric(ingate_$devname.load.load.midterm)"
      },
      {
       "target": "aliasByMetric(ingate_$devname.load.load.longterm)"
      }
     ]
    },
    {
     "title": "CPU ($cpu_value) usage on $devname",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 12 },
     "repeat": "cpu",
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "target": "alias(ingate_$devname.$cpu.cpu-steal, 'Steal')"
      },
      {
       "target": "alias(ingate_$devname.$cpu.cpu-softirq, 'SoftIRQ')"
      },
      {
       "target": "alias(ingate_$devname.$cpu.cpu-system, 'Sys')"
      },
      {
       "target": "alias(ingate_$devname.$cpu.cpu-wait, 'Wait')"
      },
      {
       "target": "alias(ingate_$devname.$cpu.cpu-user, 'User')"
      },
      {
       "target": "alias(ingate_$devname.$cpu.cpu-nice, 'Nice')"
      },
      {
       "target": "alias(ingate_$devname.$cpu.cpu-idle, 'Idle')"
      }
     ]
    }
   ]
  },
  {
   "title": "SIP Counters",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Ingress Method Counters",
   "type": "bargauge",
   "description": "Shows the current running total for SIP method types received",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias(ingate_$devname.ingate-sip-message.count-ACK-RX, 'ACK')"
    },
    {
     "target": "alias(ingate_$devname.ingate-sip-message.count-BYE-RX, 'BYE')"
    },
    {
     "target": "alias(ingate_$devname.ingate-sip-message.count-CANCEL-RX, 'CAN')"
    },
    {
     "target": "alias(ingate_$devname.ingate-sip-message.count-INFO-RX, 'INF')"
    },
    {
     "target": "alias(ingate_$devname.ingate-sip-message.count-INVITE-RX, 'INV')"
    },
    {
     "target": "alias(ingate_$devname.ingate-sip-message.count-MESSAGE-RX, 'MSG')"
    },
    {
     "target": "alias(ingate_$devname.ingate-sip-message.count-OPTIONS-RX, 'OPT')"
    },
    {
     "target": "alias(ingate_$devname.ingate-sip-message.count-PRACK-RX, 'PRK')"
    },
    {
     "target": "alias(ingate_$devname.ingate-sip-message.count-PUBLISH-RX, 'PUB')"
    },
    {
     "target": "alias(ingate_$devname.ingate-sip-message.count-REFER-RX, 'REF')"
    },
    {
     "target": "alias(ingate_$devname.ingate-sip-message.count-REGISTER-RX, 'REG')"
    },
    {
     "target": "alias(ingate_$devname.ingate-sip-message.count-SUBSCRIBE-RX, 'SUB')"
    },
    {
     "target": "alias(ingate_$devname.ingate-sip-message.count-UNKNOWN-RX, 'other')"
    }
   ]
  },
  {
   "title": "Egress Method Counters",
   "type": "bargauge",
   "description": "Shows the current running total for SIP method types sent",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias(ingate_$devname.ingate-sip-message.count-ACK-TX, 'ACK')"
    },
    {
     "target": "alias(ingate_$devname.ingate-sip-message.count-BYE-TX, 'BYE')"
    },
    {
     "target": "alias(ingate_$devname.ingate-sip-message.count-CANCEL-TX, 'CAN')"
    },
    {
     "target": "alias(ingate_$devname.ingate-sip-message.count-INFO-TX, 'INF')"
    },
    {
     "target": "alias(ingate_$devname.ingate-sip-message.count-INVITE-TX, 'INV')"
    },
    {
     "target": "alias(ingate_$devname.ingate-sip-message.count-MESSAGE-TX, 'MSG')"
    },
    {
     "target": "alias(ingate_$devname.ingate-sip-message.count-OPTIONS-TX, 'OPT')"
    },
    {
     "target": "alias(ingate_$devname.ingate-sip-message.count-PRACK-TX, 'PRK')"
    },
    {
     "target": "alias(ingate_$devname.ingate-sip-message.count-PUBLISH-TX, 'PUB')"
    },
    {
     "target": "alias(ingate_$devname.ingate-sip-message.count-REFER-TX, 'REF')"
    },
    {
     "target": "alias(ingate_$devname.ingate-sip-message.count-REGISTER-TX, 'REG')"
    },
    {
     "target": "alias(ingate_$devname.ingate-sip-message.count-SUBSCRIBE-TX, 'SUB')"
    },
    {
     "target": "alias(ingate_$devname.ingate-sip-message.count-UNKNOWN-TX, 'other')"
    }
   ]
  },
  {
   "title": "Egress Response Counters",
   "type": "bargauge",
   "description": "Shows the current running total for SIP response classes sent",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias(ingate_$devname.ingate-sip-message.count-1XX-TX, '1XX')"
    },
    {
     "target": "alias(ingate_$devname.ingate-sip-message.count-2XX-TX, '2XX')"
    },
    {
     "target": "alias(ingate_$devname.ingate-sip-message.count-3XX-TX, '3XX')"
    },
    {
     "target": "alias(ingate_$devname.ingate-sip-message.count-4XX-TX, '4XX')"
    },
    {
     "target": "alias(ingate_$devname.ingate-sip-message.count-5XX-TX, '5XX')"
    },
    {
     "target": "alias(ingate_$devname.ingate-sip-message.count-6XX-TX, '6XX')"
    }
   ]
  },
  {
   "title": "Ingress Response Counters",
   "type": "bargauge",
   "description": "Shows the current running total for SIP response classes received",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias(ingate_$devname.ingate-sip-message.count-1XX-RX, '1XX')"
    },
    {
     "target": "alias(ingate_$devname.ingate-sip-message.count-2XX-RX, '2XX')"
    },
    {
     "target": "alias(ingate_$devname.ingate-sip-message.count-3XX-RX, '3XX')"
    },
    {
     "target": "alias(ingate_$devname.ingate-sip-message.count-4XX-RX, '4XX')"
    },
    {
     "target": "alias(ingate_$devname.ingate-sip-message.count-5XX-RX, '5XX')"
    },
    {
     "target": "alias(ingate_$devname.ingate-sip-message.count-6XX-RX, '6XX')"
    }
   ]
  },
  {
   "title": "SIP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Ingress SIP method rates",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "target": "alias(ingate_$devname.ingate-sip-message.derive-ACK-RX, 'ACK')"
      },
      {
       "target": "alias(ingate_$devname.ingate-sip-message.derive-BYE-RX, 'BYE')"
      },
      {
       "target": "alias(ingate_$devname.ingate-sip-message.derive-CANCEL-RX, 'CAN')"
      },
      {
       "target": "alias(ingate_$devname.ingate-sip-message.derive-INFO-RX, 'INF')"
      },
      {
       "target": "alias(ingate_$devname.ingate-sip-message.derive-INVITE-RX, 'INV')"
      },
      {
       "target": "alias(ingate_$devname.ingate-sip-message.derive-MESSAGE-RX, 'MSG')"
      },
      {
       "target": "alias(ingate_$devname.ingate-sip-message.derive-NOTIFY-RX, 'NTF')"
      },
      {
       "target": "alias(ingate_$devname.ingate-sip-message.derive-OPTIONS-RX, 'OPT')"
      },
      {
       "target": "alias(ingate_$devname.ingate-sip-message.derive-PRACK-RX, 'PRK')"
      },
      {
       "target": "alias(ingate_$devname.ingate-sip-message.derive-PUBLISH-RX, 'PUB')"
      },
      {
       "target": "alias(ingate_$devname.ingate-sip-message.derive-REFER-RX, 'REF')"
      },
      {
       "target": "alias(ingate_$devname.ingate-sip-message.derive-REGISTER-RX, 'REG')"
      },
      {
       "target": "alias(ingate_$devname.ingate-sip-message.derive-SUBSCRIBE-RX, 'SUB')"
      },
      {
       "target": "alias(ingate_$devname.ingate-sip-message.derive-UNKNOWN-RX, 'other')"
      }
     ]
    },
    {
     "title": "Egress SIP method rates",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "target": "alias(ingate_$devname.ingate-sip-message.derive-ACK-TX, 'ACK')"
      },
      {
       "target": "alias(ingate_$devname.ingate-sip-message.derive-BYE-TX, 'BYE')"
      },
      {
       "target": "alias(ingate_$devname.ingate-sip-message.derive-CANCEL-TX, 'CAN')"
      },
      {
       "target": "alias(ingate_$devname.ingate-sip-message.derive-INFO-TX, 'INF')"
      },
      {
       "target": "alias(ingate_$devname.ingate-sip-message.derive-INVITE-TX, 'INV')"
      },
      {
       "target": "alias(ingate_$devname.ingate-sip-message.derive-MESSAGE-TX, 'MSG')"
      },
      {
       "target": "alias(ingate_$devname.ingate-sip-message.derive-NOTIFY-TX, 'NTF')"
      },
      {
       "target": "alias(ingate_$devname.ingate-sip-message.derive-OPTIONS-TX, 'OPT')"
      },
      {
       "target": "alias(ingate_$devname.ingate-sip-message.derive-PRACK-TX, 'PRK')"
      },
      {
       "target": "alias(ingate_$devname.ingate-sip-message.derive-PUBLISH-TX, 'PUB')"
      },
      {
       "target": "alias(ingate_$devname.ingate-sip-message.derive-REFER-TX, 'REF')"
      },
      {
       "target": "alias(ingate_$devname.ingate-sip-message.derive-REGISTER-TX, 'REG')"
      },
      {
       "target": "alias(ingate_$devname.ingate-sip-message.derive-SUBSCRIBE-TX, 'SUB')"
      },
      {
       "target": "alias(ingate_$devname.ingate-sip-message.derive-UNKNOWN-TX, 'other')"
      }
     ]
    },
    {
     "title": "Egress SIP response rates",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "target": "alias(ingate_$devname.ingate-sip-message.derive-1XX-TX, '1XX')"
      },
      {
       "target": "alias(ingate_$devname.ingate-sip-message.derive-2XX-TX, '2XX')"
      },
      {
       "target": "alias(ingate_$devname.ingate-sip-message.derive-3XX-TX, '3XX')"
      },
      {
       "target": "alias(ingate_$devname.ingate-sip-message.derive-4XX-TX, '4XX')"
      },
      {
       "target": "alias(ingate_$devname.ingate-sip-message.derive-5XX-TX, '5XX')"
      },
      {
       "target": "alias(ingate_$devname.ingate-sip-message.derive-6XX-TX, '6XX')"
      }
     ]
    },
    {
     "title": "Ingress SIP response rates",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "target": "alias(ingate_$devname.ingate-sip-message.derive-1XX-RX, '1XX')"
      },
      {
       "target": "alias(ingate_$devname.ingate-sip-message.derive-2XX-RX, '2XX')"
      },
      {
       "target": "alias(ingate_$devname.ingate-sip-message.derive-3XX-RX, '3XX')"
      },
      {
       "target": "alias(ingate_$devname.ingate-sip-message.derive-4XX-RX, '4XX')"
      },
      {
       "target": "alias(ingate_$devname.ingate-sip-message.derive-5XX-RX, '5XX')"
      },
      {
       "target": "alias(ingate_$devname.ingate-sip-message.derive-6XX-RX, '6XX')"
      }
     ]
    },
    {
     "title": "SIP Licenses (in use)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "target": "alias(ingate_$devname.ingate-sip-license.count-CCS, 'CCS')"
      },
      {
       "target": "alias(ingate_$devname.ingate-sip-license.count-RUS, 'RUS')"
      },
      {
       "target": "alias(ingate_$devname.ingate-sip-license.count-SRU, 'SRU')"
      }
     ]
    },
    {
     "title": "SIP Status",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "target": "alias(ingate_$devname.ingate-sip-status.count-REGISTRATIONS, 'Reg')"
      },
      {
       "target": "alias(ingate_$devname.ingate-sip-status.count-REGISTRATIONS_MAX, 'Max Reg')"
      },
      {
       "target": "alias(ingate_$devname.ingate-sip-status.count-CALLS, 'Calls')"
      },
      {
       "target": "alias(ingate_$devname.ingate-sip-status.count-CALLS_MAX, 'Max Calls')"
      },
      {
       "target": "alias(ingate_$devname.ingate-sip-status.count-CALLING, 'Calling')"
      }
     ]
    },
    {
     "title": "SIP License Usage (rate)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "target": "derivative(alias(ingate_$devname.ingate-sip-license.count-CCS, 'CCS'))"
      },
      {
       "target": "derivative(alias(ingate_$devname.ingate-sip-license.count-RUS, 'RUS'))"
      },
      {
       "target": "derivative(alias(ingate_$devname.ingate-sip-license.count-SRU, 'SRU'))"
      }
     ]
    },
    {
     "title": "SIP Status (rate)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "target": "alias(ingate_$devname.ingate-sip-status.derive-REGISTRATIONS, 'REG')"
      },
      {
       "target": "alias(ingate_$devname.ingate-sip-status.derive-CALLS, 'Calls')"
      },
      {
       "target": "alias(ingate_$devname.ingate-sip-status.derive-CALLING, 'Calling')"
      }
     ]
    }
   ]
  }
 ]
}